# Site settings
title: "Kallang's Blog"
email: kallang@outlook.com
description: "Kallang is a mobile developer, likes programming, movie, TV and sports."
baseurl: ""
url: "http://kallang.github.io"

# Build settings
markdown: kramdown
permalink: pretty
